In [1]:
from wxdata.fems.fems import(
    get_single_raws_station_weather_observations,
    get_single_raws_station_fuels_observations,
    get_multi_raws_station_weather_observations,
    get_multi_raws_station_fuels_observations,
    get_current_multi_raws_station_weather_observations,
    get_current_multi_raws_station_fuels_observations,
    get_current_all_raws_station_weather_observations,
    get_current_all_raws_station_fuels_observations,
    get_single_raws_station_nfdrs_forecast,
    get_multi_raws_station_nfdrs_forecast,
    get_single_raws_station_weather_forecast,
    get_multi_raws_station_weather_forecast
)
from wxdata.fems.meta_data import(
    get_single_raws_station_meta_data,
    get_multi_raws_station_meta_data
)

In [2]:
df, meta = get_multi_raws_station_weather_forecast([45438, 451209])

In [3]:
df

,StationName,DateTime,ObservationType,Temperature(F),RelativeHumidity(%),Precipitation(in),WindSpeed(mph),WindAzimuth(degrees),GustSpeed(mph),GustAzimuth(degrees),SnowFlag,SolarRadiation(W/m2),Tflag,RHflag,PCPflag,WSflag,WAflag,SRflag,GSflag,GAflag
161,ACTON,2026-04-08T04:00:00.000Z,F,59,34,0.00,7,280.0,9,NaN,0,39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,ACTON,2026-04-11T13:00:00.000Z,F,46,100,0.02,7,190.0,11,73.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,ACTON,2026-04-10T15:00:00.000Z,F,54,82,0.00,11,203.0,17,35.0,0,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,ACTON,2026-04-10T14:00:00.000Z,F,51,89,0.00,10,202.0,15,35.0,0,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,ACTON,2026-04-10T13:00:00.000Z,F,48,97,0.00,8,200.0,13,35.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,ABERNATHY MTN.,2026-04-12T14:00:00.000Z,F,41,84,0.01,9,207.0,18,72.0,0,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,ABERNATHY MTN.,2026-04-12T13:00:00.000Z,F,41,85,0.01,8,203.0,18,72.0,0,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,ABERNATHY MTN.,2026-04-12T12:00:00.000Z,F,40,86,0.00,8,200.0,17,72.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,ABERNATHY MTN.,2026-04-12T11:00:00.000Z,F,40,85,0.00,8,203.0,17,72.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,ABERNATHY MTN.,2026-04-08T04:00:00.000Z,F,41,70,0.00,10,310.0,18,3.0,0,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
meta

,Goober Reason,station_id,wrcc_id,period_record_start,period_record_stop,nesdis_id,station_name,state,county,latitude,...,region,unit,transmit_time,tx_frequency,obs_frequency,site_description,goes,maintenance_standard,time_zone,avg_annual_precip
0,NaN,45438,CACT,2005-01-01,2022-12-31,CA4A7044,ACTON,CA,Los Angeles,34.446389,...,CALIFORNIA,LOS ANGELES COUNTY,2.284722,60,60,"Northside of San Gabriels, in foothills of Pin...",West,Yes,PST,10.56
1,NaN,451209,WABE,2005-01-01,2022-12-31,3000B5D0,ABERNATHY MTN.,WA,Cowlitz,46.342778,...,WASHINGTON,DEPT. OF NATURAL RES,0.069444,60,60,NaN,West,Yes,PST,84.90

In [5]:
import pandas as pd

In [6]:
meta = pd.read_excel(f"FEMS Data/Station Meta Data/RAWS Meta Data.xlsx", sheet_name='Sheet1')