In [1]:
from wxdata.fems.fems import(
    get_single_raws_station_weather_observations,
    get_single_raws_station_fuels_observations,
    get_multi_raws_station_weather_observations,
    get_multi_raws_station_fuels_observations,
    get_current_multi_raws_station_weather_observations,
    get_current_multi_raws_station_fuels_observations,
    get_current_all_raws_station_weather_observations,
    get_current_all_raws_station_fuels_observations,
    get_single_raws_station_nfdrs_forecast,
    get_multi_raws_station_nfdrs_forecast,
    get_single_raws_station_weather_forecast,
    get_multi_raws_station_weather_forecast
)
from wxdata.fems.meta_data import(
    get_single_raws_station_meta_data,
    get_multi_raws_station_meta_data
)

In [2]:
df, meta = get_multi_raws_station_weather_observations([45438, 451209])

In [3]:
df

,StationName,DateTime,ObservationType,Temperature(F),RelativeHumidity(%),Precipitation(in),WindSpeed(mph),WindAzimuth(degrees),GustSpeed(mph),GustAzimuth(degrees),SnowFlag,SolarRadiation(W/m2),Tflag,RHflag,PCPflag,WSflag,WAflag,SRflag,GSflag,GAflag
167,ACTON,2026-04-01T05:00:00.000Z,O,53,90,0.04,7.0,16,13,15,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,ACTON,2026-04-03T20:00:00.000Z,O,66,13,0.00,19.0,43,36,18,0,843,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,ACTON,2026-04-03T18:00:00.000Z,O,62,17,0.00,18.0,37,44,41,0,672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,ACTON,2026-04-03T17:00:00.000Z,O,60,20,0.00,21.0,38,37,49,0,508,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,ACTON,2026-04-03T16:00:00.000Z,O,59,22,0.00,18.0,44,41,38,0,277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,ABERNATHY MTN.,2026-04-05T19:00:00.000Z,O,61,42,0.00,5.0,90,9,62,0,551,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,ABERNATHY MTN.,2026-04-05T18:00:00.000Z,O,59,42,0.00,7.0,77,10,61,0,551,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,ABERNATHY MTN.,2026-04-05T17:00:00.000Z,O,56,48,0.00,7.0,58,11,56,0,340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,ABERNATHY MTN.,2026-04-05T16:00:00.000Z,O,54,51,0.00,6.0,31,10,27,0,192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,ABERNATHY MTN.,2026-04-01T05:00:00.000Z,O,39,100,0.01,7.0,186,15,174,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
meta

,Goober Reason,station_id,wrcc_id,period_record_start,period_record_stop,nesdis_id,station_name,state,county,latitude,...,region,unit,transmit_time,tx_frequency,obs_frequency,site_description,goes,maintenance_standard,time_zone,avg_annual_precip
0,NaN,45438,CACT,2005-01-01,2022-12-31,CA4A7044,ACTON,CA,Los Angeles,34.446389,...,CALIFORNIA,LOS ANGELES COUNTY,2.284722,60,60,"Northside of San Gabriels, in foothills of Pin...",West,Yes,PST,10.56
1,NaN,451209,WABE,2005-01-01,2022-12-31,3000B5D0,ABERNATHY MTN.,WA,Cowlitz,46.342778,...,WASHINGTON,DEPT. OF NATURAL RES,0.069444,60,60,NaN,West,Yes,PST,84.90

In [5]:
import pandas as pd

In [6]:
meta = pd.read_excel(f"FEMS Data/Station Meta Data/RAWS Meta Data.xlsx", sheet_name='Sheet1')